server:
  port: ${PORT:8888}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jonathanvictoricadh/dh202302-g2-config
#          default-label: configTest
          force-pull: true
#          search-paths: